name: video
channels:
 - conda-forge
 - pytorch
dependencies:
  - python==3.7
  - pip
  - pytorch>=1.3.1
  - cudatoolkit
  - jupyter
  - ipykernel
  - torchvision>=0.4.2
  - pandas
  - opencv
  - scikit-learn
  - tqdm
  - pytest
  - papermill>=1.0.1
  - pip:
    - pytorch-ignite==0.3.0.dev20191105 # pre-release until stable available
    - fire
    - toolz
    - tabulate
    - Jinja2
    - gitpython
    - tensorboard
    - tensorboardx
    - invoke
    - yacs
    - albumentations
    - black
    - pylint
    - scipy
    - jupytext