GPUS: (0,1,2,3,4,5,6,7)
LOG_DIR: 'log/'
DATA_DIR: ''
OUTPUT_DIR: 'output/'
WORKERS: 4
PRINT_FREQ: 1000
WORLD_SIZE: 8


MODEL: 
  NAME: ilia_twostream
  EXTRA:
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      TEMPORAL_C: 
      - 16
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      TEMPORAL_C: 
      - 16
      - 8
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      TEMPORAL_C: 
      - 16
      - 8
      - 4
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      TEMPORAL_C: 
      - 16
      - 8
      - 4
      - 2
      FUSE_METHOD: SUM

CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASET:
  DATASET: 'moments'
  DATA_FORMAT: 'avi'
  ROOT: '/datasets/Moments_in_Time_Small'
  TEST_SET: 'val'
  TRAIN_SET: 'train'
  N_CLASSES: 39

TEST:
  MODEL_FILE: ''
  BATCH_SIZE_PER_GPU: 8
  NUM_WORKERS: 4
  CLIP_LEN: 32
  RESIZE_H_W: (128, 170)
  CROP_SIZE: 128

TRAIN:
  BATCH_SIZE_PER_GPU: 4
  NUM_WORKERS: 4
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: true
  CLIP_LEN: 32
  RESIZE_H_W: (128, 170)
  CROP_SIZE: 128
  OPTIMIZER: sgd
  LR: 0.03
  LR_STEP_SIZE: 15
  LR_FACTOR: 0.5
  MODEL_DIR: "model"
  
DEBUG:
  DEBUG: false